// docs/.vuepress/components/react/DemoWindow.jsx
import React, {useState, useEffect} from 'react'
import './DemoWindow.scss'

import '@st-graphics/react-scrolly/dist/bundle.css'
import StScrolly from '@st-graphics/react-scrolly'

function DemoWindow (props) {
  const [vh, setVh] = useState(0)
  useEffect(() => {
    setVh(window.innerHeight / 100)
  }, [])

  const renderBackground = (
    <div className="centered">This is a sticky background</div>
  )
  return (
    <StScrolly className="demo-window"
      renderBackground={renderBackground}
      windowHeight={60 * vh}
      windowTop={20 * vh}>
    </StScrolly>
  )
}

export default DemoWindow

// docs/.vuepress/components/DemoWindow.vue
<template>
  <st-scrolly class="demo-window" :window-height="60 * vh" :window-top="20 * vh">
    <template v-slot:background>
      <div class="centered">This is a sticky background</div>
    </template>
  </st-scrolly>
</template>

<script>
import '@st-graphics/scrolly/dist/bundle.css'
import StScrolly from '@st-graphics/scrolly'

export default {
  components: {StScrolly},
  data () {
    return {
      vh: 0
    }
  },
  mounted () {
    this.vh = window.innerHeight / 100
  }
}
</script>

<style lang="scss">
.demo-window {
  .background > div {
    background-color: red;
    height: 100%;
  }
}
</style>
